// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Options;

namespace Roslynator.Formatting
{
    internal static class CodeFormatter
    {
        public static Task<Project> FormatProjectAsync(Project project, CancellationToken cancellationToken = default)
        {
            return FormatProjectAsync(project, default(CodeFormatterOptions), cancellationToken);
        }

        public static async Task<Project> FormatProjectAsync(Project project, CodeFormatterOptions options, CancellationToken cancellationToken = default)
        {
            if (options == null)
                options = CodeFormatterOptions.Default;

            foreach (DocumentId documentId in project.DocumentIds)
            {
                Document document = project.GetDocument(documentId);

                if (options.IncludeGeneratedCode
                    || !GeneratedCodeUtility.IsGeneratedCodeFile(document.FilePath))
                {
                    SyntaxNode root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);

                    if (options.IncludeGeneratedCode
                        || !SyntaxFactsService.GetService(root.Language).BeginsWithAutoGeneratedComment(root))
                    {
                        DocumentOptionSet optionSet = await document.GetOptionsAsync(cancellationToken).ConfigureAwait(false);

                        Document newDocument = await Formatter.FormatAsync(document, optionSet, cancellationToken).ConfigureAwait(false);

                        project = newDocument.Project;
                    }
                }
            }

            return project;
        }
    }
}
