// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System;

namespace Roslynator.Formatting.CSharp
{
    public static partial class DiagnosticIdentifiers
    {
        public const string PlaceConditionalOperatorAfterExpression = "R0S0005";
        public const string RemoveNewLinesFromAccessorListOfAutoProperty = "ROS0001";
        public const string AddNewLinesToAccessorListOfFullProperty = "ROS0002";
        public const string RemoveNewLinesFromAccessor = "ROS0003";
        public const string PlaceBinaryOperatorAfterOperand = "ROS0004";
        public const string AddNewLineToEmptyBlock = "ROS1023";
        public const string AddNewLineBeforeEnumMember = "ROS1025";
        public const string AddNewLineBeforeStatement = "ROS1026";
        public const string AddNewLineBeforeEmbeddedStatement = "ROS1027";
        public const string AddNewLineAfterSwitchLabel = "ROS1028";
        public const string PlaceBinaryOperatorBeforeOperand = "ROS1029";
        public const string AddEmptyLineAfterEmbeddedStatement = "ROS1030";
        public const string AddEmptyLineBetweenDeclarations = "ROS1057";
        public const string AddNewLineToEmptyTypeDeclaration = "ROS1076";
        public const string UseLinefeedAsNewLine = "ROS1086";
        public const string UseCarriageReturnAndLinefeedAsNewLine = "ROS1087";
        public const string UseSpacesInsteadOfTab = "ROS1088";
        public const string AddEmptyLineBeforeClosingBraceOfDoStatement = "ROS1092";
        public const string AddEmptyLineAfterClosingBraceOfBlock = "ROS1153";
        public const string PlaceConditionalOperatorBeforeExpression = "ROS1184";
        public const string AddNewLinesToBlock = "ROS1185";
    }
}